//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eclipse.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1337")]
        public int Killstreaknumber {
            get {
                return ((int)(this["Killstreaknumber"]));
            }
            set {
                this["Killstreaknumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int DESERTEAGLE_SkinID {
            get {
                return ((int)(this["DESERTEAGLE_SkinID"]));
            }
            set {
                this["DESERTEAGLE_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int DUALBERETTAS_SkinID {
            get {
                return ((int)(this["DUALBERETTAS_SkinID"]));
            }
            set {
                this["DUALBERETTAS_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int FIVESEVEN_SkinID {
            get {
                return ((int)(this["FIVESEVEN_SkinID"]));
            }
            set {
                this["FIVESEVEN_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int Glock18_SkinID {
            get {
                return ((int)(this["Glock18_SkinID"]));
            }
            set {
                this["Glock18_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int AK47_SkinID {
            get {
                return ((int)(this["AK47_SkinID"]));
            }
            set {
                this["AK47_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int AUG_SkinID {
            get {
                return ((int)(this["AUG_SkinID"]));
            }
            set {
                this["AUG_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int AWP_SkinID {
            get {
                return ((int)(this["AWP_SkinID"]));
            }
            set {
                this["AWP_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int FAMAS_SkinID {
            get {
                return ((int)(this["FAMAS_SkinID"]));
            }
            set {
                this["FAMAS_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int G3SG1_SkinID {
            get {
                return ((int)(this["G3SG1_SkinID"]));
            }
            set {
                this["G3SG1_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int GALILAR_SkinID {
            get {
                return ((int)(this["GALILAR_SkinID"]));
            }
            set {
                this["GALILAR_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int M249_SkinID {
            get {
                return ((int)(this["M249_SkinID"]));
            }
            set {
                this["M249_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int M4A4_SkinID {
            get {
                return ((int)(this["M4A4_SkinID"]));
            }
            set {
                this["M4A4_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int MAC10_SkinID {
            get {
                return ((int)(this["MAC10_SkinID"]));
            }
            set {
                this["MAC10_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int P90_SkinID {
            get {
                return ((int)(this["P90_SkinID"]));
            }
            set {
                this["P90_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int MP5SD_SkinID {
            get {
                return ((int)(this["MP5SD_SkinID"]));
            }
            set {
                this["MP5SD_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int UMP45_SkinID {
            get {
                return ((int)(this["UMP45_SkinID"]));
            }
            set {
                this["UMP45_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int XM1014_SkinID {
            get {
                return ((int)(this["XM1014_SkinID"]));
            }
            set {
                this["XM1014_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int PPBIZON_SkinID {
            get {
                return ((int)(this["PPBIZON_SkinID"]));
            }
            set {
                this["PPBIZON_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int MAG7_SkinID {
            get {
                return ((int)(this["MAG7_SkinID"]));
            }
            set {
                this["MAG7_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int NEGEV_SkinID {
            get {
                return ((int)(this["NEGEV_SkinID"]));
            }
            set {
                this["NEGEV_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int SAWEDOFF_SkinID {
            get {
                return ((int)(this["SAWEDOFF_SkinID"]));
            }
            set {
                this["SAWEDOFF_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int TEC9_SkinID {
            get {
                return ((int)(this["TEC9_SkinID"]));
            }
            set {
                this["TEC9_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int P2000_SkinID {
            get {
                return ((int)(this["P2000_SkinID"]));
            }
            set {
                this["P2000_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int MP7_SkinID {
            get {
                return ((int)(this["MP7_SkinID"]));
            }
            set {
                this["MP7_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int MP9_SkinID {
            get {
                return ((int)(this["MP9_SkinID"]));
            }
            set {
                this["MP9_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int NOVA_SkinID {
            get {
                return ((int)(this["NOVA_SkinID"]));
            }
            set {
                this["NOVA_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int P250_SkinID {
            get {
                return ((int)(this["P250_SkinID"]));
            }
            set {
                this["P250_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int SCAR20_SkinID {
            get {
                return ((int)(this["SCAR20_SkinID"]));
            }
            set {
                this["SCAR20_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int SG553_SkinID {
            get {
                return ((int)(this["SG553_SkinID"]));
            }
            set {
                this["SG553_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int SSG08_SkinID {
            get {
                return ((int)(this["SSG08_SkinID"]));
            }
            set {
                this["SSG08_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int M4A1S_SkinID {
            get {
                return ((int)(this["M4A1S_SkinID"]));
            }
            set {
                this["M4A1S_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int USPS_SkinID {
            get {
                return ((int)(this["USPS_SkinID"]));
            }
            set {
                this["USPS_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("344")]
        public int CZ75Auto_SkinID {
            get {
                return ((int)(this["CZ75Auto_SkinID"]));
            }
            set {
                this["CZ75Auto_SkinID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("334")]
        public int R8REVOLVER_SkinID {
            get {
                return ((int)(this["R8REVOLVER_SkinID"]));
            }
            set {
                this["R8REVOLVER_SkinID"] = value;
            }
        }
    }
}
